sudo: required
dist: trusty

addons:
  apt:
    sources:
      - chef-current-trusty
    packages:
      - chefdk

install: echo "skip bundle install"

branches:
  only:
    - master

script: KITCHEN_LOCAL_YAML=.kitchen.dokken.yml kitchen verify ${INSTANCE}

env:
  matrix:
    - INSTANCE=default-centos-6
    - INSTANCE=default-centos-7
    - INSTANCE=default-debian-7
    - INSTANCE=default-debian-8
    - INSTANCE=default-centos-6
    - INSTANCE=default-centos-7
    - INSTANCE=default-fedora-latest
    - INSTANCE=default-ubuntu-1404
    - INSTANCE=default-ubuntu-1604
    - INSTANCE=default-opensuse-leap

before_script:
  - chef --version
  - cookstyle --version
  - foodcritic --version

matrix:
  include:
    - script:
      - chef exec delivery local all
      env:
        - UNIT_AND_LINT=1
        - CHEF_FIPS=''
